### ISSUE TITLE
地平仪的倾斜方向反了，飞行方向指示不准确

### ISSUE THREAD

**Issue by Baichuan-qiao** [MikhailTapio/FlightHud#1]
地平仪的倾斜方向放了，飞行方向指示不准确
![1690349352_258168_oJrq](https://github.com/MikhailTapio/FlightHud/assets/65058790/2af7ad62-c4c1-4a03-9b70-2e58d63b409d)

**Comment by VulpesStella** [comment]
在 flighthud.hud.min/full.toml 中，设置 pitchLadder_reverseRoll 值为 true。

**Comment by Baichuan-qiao** [comment]
这样解决不了问题吧，大佬可以重写下地平仪吗，要永远与地平线平行

**Comment by HTony03** [comment]
？改个cfg有啥难的
没必要重写 本身有cfg的 应该有这一条对应的渲染修改（不记得了 太久没看flighthud的代码了）
改改你的hud的config 就没这问题咯（应该

**Comment by Baichuan-qiao** [comment]
我改了之后没用，解决不了根本问题
