### ISSUE TITLE
可不可以延后 HUD 出现的时间？

### ISSUE THREAD

**Issue by EmptyDreams** [MikhailTapio/FlightHud#6]
装备鞘翅在地面移动时，如果不小心触发了鞘翅的飞行，HUD 会在屏幕上短暂地显示 0~1 秒的时间，相当于闪烁了一下。

能否支持开始飞行一定时间后再显示 HUD？我查看了配置文件，目前似乎并没有相关的配置。

**Comment by VulpesStella** [comment]
已在 Fabric 1.21 添加，如需向后移植请告知加载器/版本：
在 .minecraft/config/flighthud.settings.toml 中修改 hudInitializationDelay，单位为毫秒。

**Comment by EmptyDreams** [comment]
> 已在 Fabric 1.21 添加，如需向后移植请告知加载器/版本： 在 .minecraft/config/flighthud.settings.toml 中修改 hudInitializationDelay，单位为毫秒。

请求移植到 1.20.1 Fabric Loader 0.15.11

**Comment by VulpesStella** [comment]
> > 已在 Fabric 1.21 添加，如需向后移植请告知加载器/版本： 在 .minecraft/config/flighthud.settings.toml 中修改 hudInitializationDelay，单位为毫秒。
> 
> 请求移植到 1.20.1 Fabric Loader 0.15.11

好的。
另外帮我在百科条目里勾选上 Fabric 1.21 版本吧，你的提交还没过审（

**Comment by VulpesStella** [comment]
> > 已在 Fabric 1.21 添加，如需向后移植请告知加载器/版本： 在 .minecraft/config/flighthud.settings.toml 中修改 hudInitializationDelay，单位为毫秒。
> 
> 请求移植到 1.20.1 Fabric Loader 0.15.11

已在百科上传，CurseForge 审核中

**Comment by EmptyDreams** [comment]
> > > 已在 Fabric 1.21 添加，如需向后移植请告知加载器/版本： 在 .minecraft/config/flighthud.settings.toml 中修改 hudInitializationDelay，单位为毫秒。
> > 
> > 
> > 请求移植到 1.20.1 Fabric Loader 0.15.11
> 
> 好的。 另外帮我在百科条目里勾选上 Fabric 1.21 版本吧，你的提交还没过审（

已修改
